# Generated by Django 5.0.7 on 2024-07-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
